### ISSUE TITLE
please update package.js version no

### ISSUE THREAD

**Issue by mattiLeBlanc** [raix/Meteor-EventDDP#3]
Hi,

After the merge, we didn't update the version number in package.js. So Meteor doesnt notice the update and forces my to use a local package instead of the package manager.

Could you update the version and make sure it is published in Meteor's package system?

Cheers.

**Comment by rhyslbw** [comment]
FYI updating the package in Atmosphere isn't automatic by default

**Comment by mattiLeBlanc** [comment]
true, okay.
But the version number in the package.js doenst change, I reckon their would be no update trigger at all, right.

**Comment by raix** [comment]
Just published 0.0.2
